CC = gcc -Wall -std=gnu11 -ggdb

all: 
	$(CC) trucker.c -o trucker
	$(CC) loader.c -o loader
	$(CC) loader_initializer.c -o loader_initializer
clean:
	rm -f trucker
	rm -f loader
	rm -f loader_initializer
